# Generated by Django 4.2.15 on 2024-08-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="area",
        ),
        migrations.RemoveField(
            model_name="city",
            name="population",
        ),
        migrations.RemoveField(
            model_name="city",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="city",
            name="weather",
        ),
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(upload_to="city_images/"),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cities.city"
                    ),
                ),
            ],
        ),
    ]
